# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

notifications:
  email: false
  
r_packages:
  - mlr
  - dplyr
  - forestplot
  - partykit
  
r_github_packages:
  - pbiecek/breakDown
