# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

notifications:
  email: false
  
r_packages:
  - mlr
  - dplyr
  - forestmodel
  - e1071
  - breakDown
  
after_success:
  - Rscript -e 'covr::codecov()'
